export const Pismak = require('./a-pismak.jpg')
export const Yarkeev = require('./a-yarkeev.jpg')
export const Afanasiev = require('./d-afanasiev.png')
export const Tsopa = require('./e-tsopa.png')
export const Perminov = require('./i-perminov.png')
export const Klimenkov = require('./s-klimenkov.png')
export const Nikolaev = require('./v-nikolaev.jpg')
