export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const CLEAN_ERROR = 'CLEAN_ERROR'
export const LOG_OUT = 'LOG_OUT'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
