export const ADD_DOT = 'ADD_DOT'
export const DOT_SUCCESS = 'DOT_SUCCESS'
export const DOT_FAIL = 'DOT_FAIL'
export const CLEAN_DOTS_HISTORY = 'CLEAN_DOTS_HISTORY'
export const GET_DOTS = 'GET_DOTS'
export const GET_DOTS_SUCCESS = 'GET_DOTS_SUCCESS'
